## src/Stsbl/AdvancedPrivilegeBundle/Resources/config/services.yml
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\AdvancedPrivilegeBundle\:
        resource: '../../*'

    Stsbl\AdvancedPrivilegeBundle\Controller\:
        public: true
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    Stsbl\AdvancedPrivilegeBundle\EventListener\MenuListener:
        tags:
          - { name: kernel.event_listener, event: iserv_portal.menu_admin, method: onBuildAdminMenu }